<?php
	$varijable=json_decode($_POST["varijable"]); //Of course, if you are going to host AEC on your website, you should sanitize the input here...
	$kod=$_POST["kod"]; //...and here...
    	$ssid=$_POST["sessionID"];
    	if (!(((string)($ssid*1))===$ssid && $ssid>-1 && $ssid<100)) //...not only here.
        	exit("Invalid input, please access this web-page only via the web-app.");
	$datoteka=fopen("download".$ssid.".asm","w");
    	fprintf($datoteka,
            ";<pre>\n".
            ";Generated by Arithmetic Expression Compiler (http://flatassembler.000webhostapp.com/compiler.html) running in a browser with the user agent:\n".
            ";%s\n\n".
            "format PE console\n".
            "entry start\n".
            "\n".
            "include 'win32a.inc'\n".
            "\n".
            "section '.text' code executable\n".
            "start:\n\n",
            $_SERVER['HTTP_USER_AGENT']);
	for ($i=0; $i<count($varijable); $i++)
		fprintf($datoteka,
			"mov dword [esp],_izlaz%d\n".
			"call [printf]\n".
			"mov dword [esp+4],%s\n".
			"mov dword [esp],_ulaz\n".
			"call [scanf]\n\n",$i+1,$varijable[$i]);
	fprintf($datoteka,"%s\n",$kod);
	fprintf($datoteka,
		"fld dword [result]\n".
		"fst qword [esp+4]\n".
		"mov dword [esp],_izlaz\n".
		"call [printf]\n".
		"invoke system,_pause\n".
		"invoke exit,0\n".
		"\n");
	for ($i=0; $i<count($varijable); $i++)
		fprintf($datoteka,"_izlaz%d db".
		" \"Enter the value of the variable '%s': \",0\n",
		$i+1,$varijable[$i]);
	fprintf($datoteka,
		"_ulaz db \"%%f\",0\n".
		"_pause db \"PAUSE\",0\n".
		"_izlaz db \"The number on the top of the system stack is: %%f.\",10,0\n".
		"\n".
		"section '.rdata' readable writable\n".
		"result dd ?\n");
	for ($i=0; $i<count($varijable); $i++)
		fprintf($datoteka,"%s dd ?\n",$varijable[$i]);
	fprintf($datoteka,"\n".
		"section '.idata' data readable import\n".
		"library msvcrt,'msvcrt.dll'\n".
		"import msvcrt,printf,'printf',system,'system',exit,'exit',scanf,'scanf'\n".
            ";</pre>;<b>In case your browser didn't download this file, but opened it as if it was a web-page, save this file as a text-file with the extension '.asm'</b>\n");
	echo "SUCCESS!\n";
?>
